#! perl

=for comment

Simple analysis of files generated by .prof

=cut

use strict;
use warnings;

use Fatal qw(open);

my $file = shift;

open my $fh, '<', $file;

my %counts;

while (my $line = <$fh>) {
  next unless $line =~ /^### /;
  $line =~ m/^### (.*) #/;
  $counts{$1}++;
}

for my $sub (sort {$counts{$b} <=> $counts{$a}} keys %counts) {
  print "$sub : $counts{$sub}\n";
}

