#! perl

=for comment

Simple analysis of files generated by parrot's experimental
profiler.

=cut

use strict;
use warnings;

use Fatal qw(open);

open my $fh, '<', 'parrot.pprof';

my %counts;

while (<$fh>) {
  next unless /^S/;
  chomp;
  $counts{$_}++;
}

for my $sub (sort {$counts{$a} <=> $counts{$b}} keys %counts) {
  printf "%60s%10d\n", $sub, $counts{$sub};
}

