=head1 hacks.pod

=head1 WORKAROUNDS

Things that partcl has done that might be considered hacks -
things that will likely impair our ability in the distant future to
cleanly do language interoperability.

=over 4

=item user defined subs; parameter handling.

Tcl provides nice exceptions for dealing with argument handling - to continue
our example:

 % sum a b c
 wrong # args: should be "sum ?a? ?b?"

Right now, this is handled I<inside> the function definition - it is defined
to take an arbitary number of args, and then is checked for correctness
internally. It would be nice to have invoke() automatically figure this out
and generate an exception that Tcl can use.

=item flush diagnostics

At the moment, there doesn't seem to be a parrot method for determining if
a filehandle was opened for reading/writing. We can work around this by
create a parrot-specific subclass of IO and tracking the information
ourselves.

=back

=cut
